### ISSUE TITLE
Regression due to mutter upstream update

### ISSUE THREAD

**Issue by Justinzobel** [streambinder/ashtray#1]
gala: error while loading shared libraries: libmutter-2.so.0: cannot open shared object file: No such file or directory

libmutter not in your repo.

**Comment by Justinzobel** [comment]
PS I ended up stealing libmutter libraries needed for gala from the elementary ISO but obviously having libmutter properly would be better.

**Comment by streambinder** [comment]
The instance of Pantheon I have run had everything self built, nothing pre-compiled.
Checking. Will let you know.

**Comment by streambinder** [comment]
It seems this commit broke things up: [mutter@R2123:0693be4](https://dev.getsol.us/R2123:0693be46097a767ee2167ebab55d3d815c6a6ef2).
Need to keep the old version on this repository.

**Comment by Justinzobel** [comment]
Thanks for checking, let me know how you go.

**Comment by streambinder** [comment]
It seems it worked out. Doing a full repository resync and release. Will let you know, so that you can test it.

**Comment by Justinzobel** [comment]
Any update?

**Comment by Justinzobel** [comment]
Have just checked, built the mutter-2 you have in repo and working well. However now you'll need to rebuild a few things to depend on mutter-2:
- gala
- pantheon-applications-menu
- pantheon-greeter
- wingpanel
- wingpanel-indicator-a11y
- wingpanel-indicator-bluetooth
- wingpanel-indicator-datetime
- wingpanel-indicator-keyboard
- wingpanel-indicator-network
- wingpanel-indicator-nightlight
- wingpanel-indicator-notifications
- wingpanel-indicator-power
- wingpanel-indicator-privacy
- wingpanel-indicator-session
- wingpanel-indicator-sound

**Comment by streambinder** [comment]
The only correction needed over many other packages was to update `vala` dependency (such as for `wingpanel` - https://github.com/streambinder/eopkg-ashtray/commit/7b81b9da36322b10f71c19aac55a6061cc6a8799 -, `pantheon-greeter` - https://github.com/streambinder/eopkg-ashtray/commit/897461bbbda1f3fde19d89d02f09eb4987c97784 - and `pantheon-applications-menu` - https://github.com/streambinder/eopkg-ashtray/commit/6761bb82b5669378e2a1e04543db49028e3d119c). All the other issues are related to `wingpanel-*` being in the need of the newly updated `wingpanel` dependency (with very few extra cases for `switchboard-plug-parental-controls` - https://github.com/streambinder/eopkg-ashtray/commit/aa6650d03856c59283bb0e362d2f70352f8714b2 - and `pantheon-default-settings` - https://github.com/streambinder/eopkg-ashtray/commit/fc5127e22fa647ff183c9a1d01088590ce730434).
In the morning I will make a new release with all those changes, anyway.

**Comment by Justinzobel** [comment]
Excellent, thanks for the update!

**Comment by streambinder** [comment]
Hey @Justinzobel, I just released `v13` version, including really lot of updates, but the most breaking one is the already referenced `mutter` downgrade in a dedicated `mutter-2` package. Also, now you should be able to install the whole Pantheon desktop dependency tree as package group, using this command:
```
eopkg it -c desktop.pantheon
```
Would you mind to test it?

**Comment by Justinzobel** [comment]
I'll re-try this shortly.

**Comment by Justinzobel** [comment]
```
sudo eopkg it -c desktop.pantheon
The following package(s) are already installed and are not going to be installed again:
pantheon-screenshot
Following packages will be installed:
accountsservice            alsa-lib                         avahi                              cerbere                         contractor                       folks                            font-raleway-ttf                           
gala                       gdbm                             libaccounts-glib                   libchamplain                    libsignon-glib                   lightdm                          linux-driver-management-lightdm-integration
mutter-2                   pantheon-applications-menu       pantheon-calendar                  pantheon-capnet-assist          pantheon-default-settings        pantheon-dpms-helper             pantheon-greeter                           
pantheon-session-settings  pantheon-shortcut-overlay        pantheon-sound-theme               pantheon-stylesheet             pantheon-wallpapers              pulseaudio                       switchboard                                
switchboard-plug-a11y      switchboard-plug-about           switchboard-plug-applications      switchboard-plug-bluetooth      switchboard-plug-datetime        switchboard-plug-display         switchboard-plug-keyboard                  
switchboard-plug-locale    switchboard-plug-mouse-touchpad  switchboard-plug-network           switchboard-plug-notifications  switchboard-plug-onlineaccounts  switchboard-plug-pantheon-shell  switchboard-plug-parental-controls         
switchboard-plug-power     switchboard-plug-printers        switchboard-plug-security-privacy  switchboard-plug-sharing        switchboard-plug-sound           switchboard-plug-useraccounts    wingpanel                                  
wingpanel-indicator-a11y   wingpanel-indicator-bluetooth    wingpanel-indicator-datetime       wingpanel-indicator-keyboard    wingpanel-indicator-network      wingpanel-indicator-nightlight   wingpanel-indicator-notifications          
wingpanel-indicator-power  wingpanel-indicator-privacy      wingpanel-indicator-session        wingpanel-indicator-sound       xapian-core                      zeitgeist                      
Total size of package(s): 46.87 MB
```

**Comment by Justinzobel** [comment]
That what you were expecting? I'll try actually install it all in a VM soon.

**Comment by streambinder** [comment]
I need to know if the installation process goes well and/or if the DE starts correctly. Thank you.

**Comment by Justinzobel** [comment]
OK, sorry for the delay. Got my main PC back up and running and have tested in a clean Solus VM.

DE starts OK but you might consider adding `elementary-icon-theme` to the component if you can, it's needed to ensure the icons are displaying properly on wingpanel. You may need to have elementary-icon-theme in your repo to do it, it'd be easy enough and just set your release number 100 higher than the Solus default so it's picked instead of the in-repo version.

Also the fonts default to Open Sans and Roboto Mono, both of which don't exist so terminal fonts look bad. You could fix this by creating a schema to override them for some standard ones, but that's up to you.

**Comment by Justinzobel** [comment]
I've set fonts to:
Interface Text: Clear Sans Regular 9
Document Text: Clear Sans Regular 10
Monospace Text: Monospace Regular 10

All looks OK. These are in the default install of Solus Budgie.

Also of note is not using the pantheon greeter. Still lightdm. Any thoughts on that?

**Comment by streambinder** [comment]
Perfect. Very good job, dude. Thank you.
Setting this as closed then, and scheduling activities about fonts and greeter (which I actually think its just an issue of OS selection). If you find a way to enable/switch then, ping me.

**Comment by streambinder** [comment]
@Justinzobel with last commits I should've fixed fonts/icons issues and corrected component maintainer.
Would you please test again upon last release? Also, about `pantheon-greeter`, once installed `desktop.pantheon` component, would you please edit `/usr/share/lightdm/lightdm.conf.d/60-slick-greeter.conf`, set `greeter-session=pantheon-greeter` to check if that's the last thing missing to have Pantheon Greeter as default?
If so, I would also check if creating a /usr/share/lightdm/lightdm.conf.d/61-pantheon-greeter.conf`with the content above actually overrides the `slick-greeter`:
```
# We only exist to override the default greeter to be the slick-greeter

[Seat:*]
greeter-session=pantheon-greeter
```

Thank you, let me know.

**Comment by Justinzobel** [comment]
Your webserver is down currently :disappointed:

**Comment by streambinder** [comment]
I know, had some issue during the night.
It's ok, now. 👍🏻

**Comment by Justinzobel** [comment]
Tried a few ways but it wouldn't display anything for me. Might have to tinker with an elementary ISO in VM maybe to find the right settings.

**Comment by streambinder** [comment]
Few ways to do what, exactly? Are fonts clear now? And icons? Are you talking about Pantheon Greeter?

**Comment by Justinzobel** [comment]
Sorry, that was very vague. Fonts are OK except terminal font, pantheon-greeter is what I had trouble with, whenever I set it in any config file and restart lightdm it goes black.

Screenshot of the terminal:
![image](https://user-images.githubusercontent.com/1370117/59415635-0287a180-8e03-11e9-8bf4-a8c5b47f7a1c.png)

**Comment by streambinder** [comment]
Which terminal are you using? Gnome or Pantheon? Do they behave the same about fonts?
Does Pantheon use its own (new) icons?
About Greeter, yup, we need to look into it deeper.

**Comment by Justinzobel** [comment]
Both gnome-terminal and pantheon-terminal.

**Comment by Justinzobel** [comment]
So the fonts you need are open-sans and roboto mono:
https://fonts.google.com/specimen/Roboto+Mono
https://fonts.google.com/specimen/Open+Sans

**Comment by streambinder** [comment]
Fonts should be pulled as per `pantheon-default-settings` runtime dependencies: https://github.com/streambinder/ashtray/blob/master/src/pantheon-default-settings/package.yml#L12.

**Comment by streambinder** [comment]
I think the problem with `pantheon-greeter` is about `mutter-2`. If you try to install it over a working environment, it fails because it should overwrite files belonging to upstream `mutter` package.
It seems some files aren't correctly isolated to `-2` suffix.
I think I'll try to patch `pantheon-greeter` to work with newer `mutter` releases.

**Comment by streambinder** [comment]
It's not feasible, as many others are depending on `mutter-2`. Need to investigate.

**Comment by Justinzobel** [comment]
Yeah, I have to remove mutter before installing mutter-2 due to conflicts. But that's OK.

**Comment by Justinzobel** [comment]
Regarding the fonts in https://github.com/streambinder/ashtray/blob/master/src/pantheon-default-settings/package.yml#L12 you've got Clear Sans and Roboto, but you need **Open** Sans and Roboto **Mono**

**Comment by Justinzobel** [comment]
There is a way to conflict the package so that it will prompt the user to remove mutter in place of mutter-2, have a look at the lightdm/gdm driver packages in the main repo for how to do that.

**Comment by Justinzobel** [comment]
https://fonts.google.com/download?family=Roboto%20Mono
https://fonts.google.com/download?family=Open%20Sans
Package those, licenses are distributable under Apache 2.0 in your repo, add them to the rundep, bump version of pantheon-default-settings and should be good.

**Comment by streambinder** [comment]
Ok, fonts are up. Would you test?
Updated also `mutter-2` to avoid files conflicting with `mutter`.

**Comment by Justinzobel** [comment]
I'll have a test when I get home or tomorrow.

**Comment by streambinder** [comment]
Once you tested fonts, please, test installing this `pantheon-greeter` (obviously, rename from `.txt` to`.eopkg`) version: [pantheon-greeter-3.3.1-3-1-x86_64.eopkg](https://github.com/streambinder/ashtray/files/3290566/pantheon-greeter-3.3.1-3-1-x86_64.txt). It brings all the stuff needed to make it be called instead of `slick` (default) one.

**Comment by Justinzobel** [comment]
Couldn't get it to work on my existing install so went back to a snapshot and installed the `desktop.pantheon` component again but got an error:
```
Downloading 11 / 62
Package wingpanel-indicator-power found in repository streambinder
wingpanel-indicator-power-2.1.4-2-1-x86_64.eopkg (81.0 KB)100%    273.59 MB/s [00:00:00] [complete]
Program terminated.
Download Error: Package does not match the repository package.
```

**Comment by Justinzobel** [comment]
Seems sha1sum is wrong, try updating the eopkg index.

**Comment by streambinder** [comment]
Rebuilt the whole repository and pushed a new release. Could you retry?

**Comment by Justinzobel** [comment]
I've just installed, rebooted and just got black screen. What release of pantheon-greeter should it be on?

**Comment by Justinzobel** [comment]
I'm getting this in dmesg: `[  634.922292] traps: io.elementary.g[1155] trap int3 ip:7f37ac132325 sp:7fff85164ed0 error:0 in libglib-2.0.so.0.6000.4[7f37ac0f8000+81000]
`

**Comment by streambinder** [comment]
Will look into it.
