### ISSUE TITLE
Component not found for desktop.pantheon

### ISSUE THREAD

**Issue by ZachBacon** [streambinder/ashtray#11]
eopkg reports as no component named desktop.pantheon, and seems installing the packages result in a desktop environment that doesn't load wingpanel

**Comment by ZachBacon** [comment]
actually as for the individual packages, seems I forgot 2, cebere and contractor, things work now, however the component issue is still the main issue

**Comment by streambinder** [comment]
Thank you for reporting. It's a simple repository index non-alignment: I'm triggering a new release with a fixed index. It will be available in few minutes.
