### ISSUE TITLE
Add support for Deepin desktop

### ISSUE THREAD

**Issue by ghost** [streambinder/ashtray#17]
hi can u create deepin-wm for solus

https://github.com/linuxdeepin/deepin-wm

this is the most beautiful wm out there

**Comment by Justinzobel** [comment]
I have started packaging the Deepin desktop but it's still in the early stages, I'll leave this open and let you know how I go.

**Comment by Justinzobel** [comment]
Quick teaser ;)

![VirtualBox_Solus Deepin_27_01_2020_10_03_55](https://user-images.githubusercontent.com/1370117/73143628-5aea8580-40ec-11ea-9613-4df2667c6f48.png)

**Comment by ghost** [comment]
cool cant wait

**Comment by Justinzobel** [comment]
I am still working on getting this into the repo, doing license verification currently. Should have it in soon.

**Comment by Justinzobel** [comment]
Why close it?

**Comment by Justinzobel** [comment]
No longer interested in DDE? OK I'll stop working on it.

**Comment by ghost** [comment]
I already have it on my repo soo..
