### ISSUE TITLE
How to use commands.yml file ?

### ISSUE THREAD

**Issue by ghost** [streambinder/ashtray#18]

**Comment by Justinzobel** [comment]
commands.yml? Ah a zeus question, that's for @streambinder

**Comment by ghost** [comment]
> commands.yml? Ah a zeus question, that's for @streambinder

yea the God command

**Comment by streambinder** [comment]
The `commands.yml` file is defining actions such as `setup`, `update`, and so on.
You can call each by running `zeus command`, e.g., `zeus release`.

**Comment by ghost** [comment]
ah its https://github.com/dreadl0ck/zeus ?

**Comment by streambinder** [comment]
Yeah, it's a replacement for the traditional `Makefile`.

**Comment by ghost** [comment]
okey thank you soo much
