### ISSUE TITLE
Cinnamon Settings won't open

### ISSUE THREAD

**Issue by justnext** [streambinder/ashtray#19]
Salve,

When started from the menu, Cinnamon Settings silently fails.  Settings window does not open.

When started from terminal, the following error is returned:
```
$ cinnamon-settings
True
Traceback (most recent call last):
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 726, in <module>
    window = MainWindow()
  File "/usr/share/cinnamon/cinnamon-settings/cinnamon-settings.py", line 309, in __init__
    for module in modules:
  File "/usr/share/cinnamon/cinnamon-settings/modules/cs_themes.py", line 8, in <module>
    from CinnamonGtkSettings import CssRange, CssOverrideSwitch, GtkSettingsSwitch, PreviewWidget, Gtk2ScrollbarSizeEditor
  File "/usr/share/cinnamon/cinnamon-settings/bin/CinnamonGtkSettings.py", line 6, in <module>
    import tinycss
ModuleNotFoundError: No module named 'tinycss'
$ 
```
`python-tinycss-0.4-1-1-x86_64.eopkg` package is at the recent version.

Checking the system with `sudo eopkg check` returns only `udisks` package as "Broken". It is considered as a normal situation in Solus. `udisks` is not Cinnamon- or python-related.  The system is clean.

The following actions have been taken.  None of them solves the issue:

- re-installation of the `python-tinycss` package
- re-installation of the `python` package
- re-installation of the `python3` package
- re-installation of the `desktop.cinnamon` component
- complete removal and installation from scratch of the `desktop.cinnamon` component

Thank you very much for making Cinnamon available in Solus.  It is highly appreciated.

**Comment by streambinder** [comment]
This is probably related to the recent Python stack changes from the Solus core team.
If I'm not wrong, `python-tinycss` just needs to be rebuilt against recent upstream dependencies.
@Justinzobel, can you give it a try?

**Comment by justnext** [comment]
Yes, it is surely related to Python changes in Solus.  There were other errors, not Cinnamon-related, due to this fact.

Unfortunately, I'm neither Python- nor Linux-dev (I'm a fossil from mainframe, OS-390, z/OS, Cobol2, CICS, IBM DB2, JCL world), so can't quickly rebuild `python-tinycss` - I simply don't know how to do that.

_Edit_: Sorry, reading quickly, I was confused between two similar addressees, @Justinzobel and @justnext.

**Comment by Justinzobel** [comment]
I'll have a look shortly.

**Comment by justnext** [comment]
OMG, you're [@Justin](https://discuss.getsol.us/u/Justin) from Solus forum :-) !  Max respect!

There's no hurry at all.

**Comment by Justinzobel** [comment]
Indeed I am. @streambinder can you build python-tinycss and python-pam, I have bumped their release numbers, issue is due to the python 3.7 upgrade, paths change, they will update when they build.

**Comment by streambinder** [comment]
> Issue is due to the python 3.7 upgrade, paths change, they will update when they build.

Exactly what I meant.
Our sources don't need any change, build toolchain will take care of installing them in the right updated location.

In either case, I'm trying to follow the same approach as the core team for rolling repository updates out: new release coming on friday afternoon. Expect the update to come in that day.

@justnext as soon as you update and are able to test it, let us know.

**Comment by justnext** [comment]
> ...as soon as you update and are able to test it, let us know.

Yes, sure, I will.  As soon as update will arrive - around friday afternoon or saturday morning, - I'll report the result back here.  Thank you both for attention and dedication.

**Comment by streambinder** [comment]
You're welcome. Thanks for reporting.

**Comment by streambinder** [comment]
@justnext, new release pushed.

**Comment by justnext** [comment]
As expected, three packages were upgraded to higher release numbers.  From upgrade log:

```
Installing nemo, version 4.4.2, release 4
Installing python-pam, version 1.8.4, release 2
Installing python-tinycss, version 0.4, release 2
```
The issue with not opening `cinnamon-settings` is solved.  Cinnamon Settings opens from menu and terminal now.

There were two other issues, which I didn't report earlier.  Doing right mouse click on a panel and selecting either "Panel settings" or "Applets" options from the popup menu didn't open neither Panel nor Applets settings dialogs.  I suspected that both were related to Python changes too.

Both issues are solved now as well.  Panel and Applets dialogs are opened and work as they should.

All three issues are completely solved.  Thanks again!

The topic may be closed.

**Comment by Justinzobel** [comment]
Please report them next time in case they're not related. But great to hear
they're all solved.
