### ISSUE TITLE
XFCE packages complain about libxfce4util

### ISSUE THREAD

**Issue by Phantop** [streambinder/ashtray#26]
Installing just about any of the packages included in desktop.xfce throws this error with eopkg:

```
System error. Program terminated.
libxfce4util release >= 2 dependency of package thunar is not satisfied
Please use 'eopkg help' for general help.
Use --debug to see a traceback.
````

The error occurs even if libxfce4util is installed. Also, I'm using the unstable Solus repository, so that may be impacting things, though I doubt it since libxfce4util is part of this repo.

**Comment by streambinder** [comment]
You're right, this is not related to official Solus repository.
Thanks for the report, will look into it.

**Comment by Justinzobel** [comment]
Working on this. I'm renaming libxfce4util to at-libxfce4-util so it doesn't conflict with the one in the Solus repository. Have also asked Solus to deprecate libxfce4-util as it's not used in their repo for anything.

Will push commits today.

**Comment by Justinzobel** [comment]
This should fix the issue https://github.com/streambinder/ashtray/commit/b43516d5e3913a3f2f0b3a29de4737b2fafbbc8c @streambinder can you please run a build and push them.

**Comment by streambinder** [comment]
@Phantop now you should be able to install. Please try, and let us know.

**Comment by Phantop** [comment]
Yep, thunar installed no problem, at least.
