### ISSUE TITLE
Cinnamon 4.6 applets aren't configurable

### ISSUE THREAD

**Issue by justnext** [streambinder/ashtray#29]
It's currently impossible to open configuration settings for applets, desklets, extensions in Cinnamon 4.6.

It's not Solus but an upstream issue, currently present in various systems with Cinnamon 4.6:

- LinuxMint (Ubuntu-based)
- Arch Linux
- Solus

The [issue #9305](https://github.com/linuxmint/cinnamon/issues/9305), already closed, is reported to Cinnamon GitHub 3 days ago.  It will be presumably fixed by the [commit #9306](https://github.com/linuxmint/cinnamon/pull/9306).

For now, neither LinuxMint nor Arch Linux have received the patch.  When the patch will become available, it would be nice to have it applied also in Solus Cinnamon 4.6.

Thanks for reading

**Comment by Justinzobel** [comment]
Thanks for the research and report @justnext. I've subscribed myself to both the upstream issue and pull request to monitor it and as soon as it's confirmed to fix the issue we'll get it into our package.

**Comment by justnext** [comment]
I noticed the patch landed in Arch Linux today, March 18, at around 06:00 UTC = 06:00 GMT = 16:00 Sydney, New South Wales, Australia.

They rebuilt `cinnamon-4.6.0-2` package, incrementing the build number from **2** to **3**.  Config settings are operational again in their [cinnamon-4.6.0-3](https://www.archlinux.org/packages/community/x86_64/cinnamon/) package.

Just for your information.  There's no hurry at all.

**Comment by Justinzobel** [comment]
Have added the patch https://github.com/streambinder/ashtray/commit/31d75bfc6b9bb96bc59a347dc1ed06bafa6e7f03 @streambinder can you please advise once built and available for @justnext.

**Comment by streambinder** [comment]
Sure. Will ping back after releasing.

**Comment by Justinzobel** [comment]
@streambinder Is this now in the repo?

**Comment by streambinder** [comment]
Nope, it won't be until Friday.

**Comment by streambinder** [comment]
@justnext a new release got on the way. Can you please update and keep us posted about the result you get now?

**Comment by justnext** [comment]
I'm not in the city right now, out of civilization.  I'll report back as soon as return to computers.  Hope to return back to life in three days, around 27 May 2020.

Thanks a lot, Justin.
Grazie mille, Davide.

Огромное спасибо обоим.  State facendo un lavoro inestimabile.

24 May 2020, UTC 07:00, GMT 07:00, 09:00 Rome local time, 17:00 Canberra local time

**Comment by Justinzobel** [comment]
I'm so confused, are you Russian, Italian or Australian? :smile:

**Comment by justnext** [comment]
Thanks for your intervention(s), the problem in Solus Cinnamon 4.6.0 release 7 is perfectly solved.  Everything works fine.  Applets, desklets, extensions can be configured again.

The issue is solved.  The topic may be closed.

Grazie di cuore ad entrambi!  Thank you both!

26 May 2020,  UTC 10:10,  GMT 10:10,  12:10 Roma ora locale,  20:10 Canberra local time
