### ISSUE TITLE
Violation of MegaSync's License

### ISSUE THREAD

**Issue by DataDrake** [streambinder/ashtray#4]
I am not affiliated with MegaSync, but as a developer for Solus I have to inform you that you are in violation of the MegaSync license by redistributing the software in its compiled form.

> Subject to the terms of this licence, we grant you a non-transferable, non-exclusive, worldwide, royalty-free licence to access and use the code solely for review purposes.

**Comment by streambinder** [comment]
You're right. Just to know, in your opinion, producing `eopkg` from official prebuilt `deb` would violate the license anyway?

**Comment by DataDrake** [comment]
That one I'm a little fuzzy on. I suggest you ask them over on their GitHub repo.

**Comment by streambinder** [comment]
Will surely do it. Thank you.
