### ISSUE TITLE
VSCodium error : execvp: Format error for exec()

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [streambinder/ashtray#48]
![](https://user-images.githubusercontent.com/13170204/95677715-b2bc1480-0bc7-11eb-9302-aa4954ddf282.png)

VSCodium seems to have issues in the latest build.

**Comment by PoorPocketsMcNewHold** [comment]
Btw, may your rebuild the package manually from your repos servers, please? I don’t think they are, many users, using Solus on an arm machine.

**Comment by streambinder** [comment]
The package is automatically built and deployed on unstable the moment a change is pushed on master (https://github.com/streambinder/theca/runs/1238630255?check_suite_focus=true).
For stable, it's deployed on Friday.
