### ISSUE TITLE
Gnome 3.38 breaks Cinnamon

### ISSUE THREAD

**Issue by justnext** [streambinder/ashtray#53]
27 November 2020 Gnome stack was [upgraded](https://getsol.us/2020/11/26/endless-de-ssert-the-roundup-17/) from 3.36 to 3.38 in Solus.  It was a massive upgrade.  The number of upgraded packages varies from 125 to 350, depending on DE.

Solus Cinnamon was working perfectly prior to upgrade.  Unfortunately, the upgrade has broken it.  An attempt to start Cinnamon session brings the infamous window:

```
You are currently running in fallback mode.
...
Do you want to restart Cinnamon?

No  Yes
```
Clicking Yes brings the same window back again - Cinnamon doesn't start up.  Clicking No leads to black unusable screen; X-session restart with Ctrl+Alt+BkSp is the only way to get out of it.

Due to a high number of upgrades it's difficult to individuate the offending package(s).  Removing and re-installing Cinnamon doesn't fix the issue.

Solus is useless without Cinnamon.

Thanks for reading

**Comment by algent-al** [comment]
Hey @justnext are you able to rollback the update? I think the whole cinnamon stack need a rebuild.
Another thing you can do is to make sure that there isn't any broken package.

**Comment by justnext** [comment]
> Hey @justnext are you able to rollback the update?...

Yes, surely I can.  I already restored Cinnamon partition from the pre-upgrade backup, and now replying from working, not yet upgraded Cinnamon.

There was only one broken `pam` package.  I completely removed and re-installed it back again.  Checked the system a second time with `sudo eopkg check`.  No broken pkgs this time.

I'm backing up the clean, perfectly working Cinnamon partition again.  It'll take about 20 minutes.

Once backup is completed, I'll upgrade Cinnamon again, and will report back here later.

Thanks for attention

**Comment by justnext** [comment]
Before upgrading Cinnamon, I checked it for broken packages again.  No broken pkgs were present.

The upgrade was finished in a clean way, without a single hickup.  158 pkgs were downloaded and installed in less than 10 minutes.

Unfortunately, Cinnamon still doesn't want to start up after reboot.  It presents the same `You are currently running in fallback mode` window as in OP.

You're right, seems like Cinnamon stack needs a rebuild.

Thank you

**Comment by justnext** [comment]
Before upgrading Cinnamon, I checked it for broken packages again.  No broken pkgs were present.

The upgrade was finished in a clean way, without a single hickup.  158 pkgs were downloaded and installed in less than 10 minutes.

Unfortunately, Cinnamon still doesn't want to start up after reboot.  It presents the same `You are currently running in fallback mode` window as in OP.

You're right, seems like Cinnamon stack needs a rebuild.

Thank you

**Comment by streambinder** [comment]
Will bump all the Cinnamon stack, so to trigger a rebuild and check whether there's something wrong or not.
Thanks for reporting, @justnext, by the way.

**Comment by justnext** [comment]
After the regular Friday's Solus upgrade on 27 November 2020, there was a second upgrade on 29 November 2020.  The second upgrade wasn't announced neither in forum, nor in Dev Tracker.

Two upgraded packages are from Gnome 3.38 stack:
- mutter = Gnome Shell compositing window manager
- libgnome-desktop = Gnome utility runtime library

Other upgraded pkgs are mostly multimedia-related:
- dav1d
- ffmpeg
- libheif
- vapoursynth
- imagemagick
- eom
- vlc

Hopefully, the "silent" `mutter` and `libgnome-desktop` upgrade won't affect Cinnamon rebuild process.

With respect

**Comment by streambinder** [comment]
Shouldn't affect it, as non Cinnamon component is pulling those as dependencies.

**Comment by streambinder** [comment]
@justnext upgrade just rolled out on unstable: please, test it out and report if you still can't access your Cinnamon instance after the upgrade.

**Comment by justnext** [comment]
@streambinder Gnome upgrade to 3.38 was delayed, to avoid breaking Cinnamon.  As upgraded Cinnamon is available from Streambinder Unstable now, two subsystems were upgraded at the same time:

- (delayed) Gnome to 3.38.1 from SolusStable, and
- Cinnamon to 4.8.0-12 from StreambinderUnstable

Cinnamon doesn't fail on start up anymore.  It works normally again, and is fully operational.  OP issue is fixed.  For me, it can be pushed to Streambinder Stable.

Thank you!

**Comment by streambinder** [comment]
Cool, closing the issue then.
Rolling on stable will happen on Friday, as usual.
