### ISSUE TITLE
Introducing xfconf in offical Repo

### ISSUE THREAD

**Issue by algent-al** [streambinder/ashtray#57]
By updating `catfish` to 4.16.0, a new dependency is required `xfconf`. This package is in Theca repository and I propose to remove it from here if the patch of `catfish` is landed in Solus stable repository. See the stack here: https://dev.getsol.us/D10429

Also part of this is the update to 4.16.0 of `libxfce4util` package which in Theca is named as `at-libxfce4util`.

**Comment by streambinder** [comment]
Thanks for reporting.
As soon as `libxfce4util` will be updated to 4.16.x series (saw this is awaiting for approval: https://dev.getsol.us/D10427), we will drop our `xfconf` and `at-libxfce4util`.
If that won't be the case, we will be in the need of turning `xfconf` into `at-xfconf` as well.

Can you keep this issue aligned if there are any updates, please?

**Comment by algent-al** [comment]
No problem, I will report back for any change.

**Comment by algent-al** [comment]
Update: 
`xfconf` is now available in the Unstable Repository https://dev.getsol.us/source/xfconf/
`libxfce4util` is updated to 4.16.0 https://dev.getsol.us/source/libxfce4util/

My consern is that `xfconf` in Theca is `release    : 5` and official package is `release    : 1`. This will be a problem because users that had `xfconf` installed from Theca repository will not see any update of it until official `xfconf` reach `release    : 6`.
I think that this can be solved if we post a note in README.md file in this repo to warn them to force reinstall `xfconf` with this command: `sudo eopkg it --reinstall xfconf`.

**Comment by streambinder** [comment]
> xfconf is now available in the Unstable Repository https://dev.getsol.us/source/xfconf/
> libxfce4util is updated to 4.16.0 https://dev.getsol.us/source/libxfce4util/

Awesome, let's just wait until Friday to drop them (is the unstable going to be rolled-out on Friday, right?) from Theca.

> My consern is that xfconf in Theca is release : 5 and official package is release : 1.

Agreed.
On the other hand though, with our package they already are on the latest version, so it shouldn't be a big deal of a problem (at least on the current state of things, probably things are going to be really messed up between release 2 and 6, during which they will stick to our no-more-up-to-date version, but I don't think this case is really worth the headache of handling it).
I think the best approach is just to let things go naturally and if anybody is going to experience issues related to this, they'll open an issue here to which we will remember to reply with the `--reinstall` solution you mentioned.

**Comment by algent-al** [comment]
> is the unstable going to be rolled-out on Friday, right?

I think the sync will be this Friday or maybe Saturday morning. There was no major change in Repository to postpone it next week.

**Comment by streambinder** [comment]
> I think the sync will be this Friday or maybe Saturday morning. There was no major change in Repository to postpone it next week.

Alright then, we got to wait until everything is rolled-out on stable, as Theca is based off Solus' stable branch.
I'm not currently on Solus, though: can you ping here as soon as you notice the roll-out has been done on stable? So that I can kick the affected packages here out on Theca and polish things up.

**Comment by algent-al** [comment]
Sync just finished. Now you can go ahead with Theca changes.

**Comment by streambinder** [comment]
@algent-al apparently upstream `libxfce4util-devel` is not exposing Vala bindings, resulting in build failures here on packages which depend on that, as you can see on last [goldsmith action run](https://github.com/streambinder/theca/runs/1793983526#step:9:2304).
The package gotta be compiled expanding the [`%configure`](https://dev.getsol.us/source/libxfce4util/browse/master/package.yml$13) step with the `--enable-vala` flag option.

**Comment by algent-al** [comment]
I think you should revert `libxfce4util` to `at-libxfce4util`.

**Comment by streambinder** [comment]
I will probably try to wrap Vala API only packaging `libxfce4util` into `libxfce4util-vala`. I'll see.

**Comment by algent-al** [comment]
Yes, that is a solution too.
