### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by Justinzobel** [streambinder/ashtray#6]
https://github.com/elementary/pantheon-agent-geoclue2/releases/tag/1.0.2

https://github.com/elementary/stylesheet/releases/tag/5.2.4

https://github.com/elementary/wingpanel/releases/tag/2.2.5

https://github.com/elementary/wingpanel-indicator-session/releases/tag/2.2.4

https://github.com/elementary/cerbere/releases/tag/2.5.0

https://github.com/elementary/icons/releases/tag/5.0.4

**Comment by streambinder** [comment]
Good. As I have free time, I will update.

**Comment by Justinzobel** [comment]
Have started a build of the full stack with these updates, will advise soon if it's all OK.

**Comment by Justinzobel** [comment]
Had to adjust the two font sha256sums as they seem to have changed

Then when building mutter-2 I get *** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.20

**Comment by streambinder** [comment]
> Had to adjust the two font sha256sums as they seem to have changed

Yeah, I know. It's really a shame to need to forcely change it anytime you build it, but I haven't found another way to download them.

> Then when building mutter-2 I get *** error: gettext infrastructure mismatch: using a Makefile.in.in from gettext version 0.19 but the autoconf macros are from gettext version 0.20

Damn it, `mutter-2` is giving me too much headaches. I really hope elementary's team will speed up the patching process of their softwares to support newer versions.

**Comment by Justinzobel** [comment]
Unlikely they'll speed up, they're based on an LTS Ubuntu which is always going to be behind.

**Comment by streambinder** [comment]
Dependencies updated.

**Comment by Justinzobel** [comment]
Thanks for doing this, had a bit of a break from the PC, a digital detox of sorts.
