### ISSUE TITLE
Cannot add Google Account in Switchboard

### ISSUE THREAD

**Issue by Justinzobel** [streambinder/ashtray#8]
Error when launched in terminal: `** (io.elementary.switchboard:24973): CRITICAL **: 16:45:59.855: Account.vala:103: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityStoreFailed: Failed to store identity`

**Comment by streambinder** [comment]
Need to look into it, but maybe something like [this](https://github.com/elementary/switchboard-plug-onlineaccounts/issues/76#issuecomment-438574382) will help us.

**Comment by streambinder** [comment]
Hey @Justinzobel, would you please test the attached `eopkg` ? The manifest used to build it is attached, too (it basically applies the build flags reported in the issue I pointed out on the comment above).
- [gsignond-1.2.0-2-1-x86_64.eopkg](https://github.com/streambinder/ashtray/files/3430486/gsignond-1.2.0-2-1-x86_64.eopkg.txt)
- [gsignond-devel-1.2.0-2-1-x86_64.eopkg](https://github.com/streambinder/ashtray/files/3430487/gsignond-devel-1.2.0-2-1-x86_64.eopkg.txt)
- [package.yml](https://github.com/streambinder/ashtray/files/3430488/package.yml.txt)

Let me know as soon as possible.

PS: I used `txt` to workaround the GitHub file upload block.

**Comment by Justinzobel** [comment]
Progress but no cigar:
```
** (io.elementary.switchboard:1382): CRITICAL **: 16:27:51.994: Account.vala:103: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.MethodNotKnown: authentication method 'oauth' doesn't exist
```

**Comment by Justinzobel** [comment]
A bit of looking around didn't find anything relevant but I did find this which will likely be of interest https://github.com/orgs/elementary/projects/46

**Comment by streambinder** [comment]
If I'm not mistaken the error suggests that what should be providing OAuth API is not actually doing it: that module should be provided by `gsignond-plugin-oauth` package. I guess there's a misconfiguration on the `switchboard` package dependency tree.
Would you please assure you have `gsignond-plugin-*` installed and retry? If that's the case, I'll proceed to add the `rundep` adequately.

**Comment by Justinzobel** [comment]
Progress again, installed gsignond-plugin-oauth and re-booted, ran switchboard and tried to add Google Account.

Tried eopkg install -c desktop.pantheon but it didn't install any gsignond packages.

Error: `** (io.elementary.switchboard:1250): CRITICAL **: 13:07:02.172: Account.vala:103: GDBus.Error:com.google.code.AccountsSSO.gSingleSignOn.Error.IdentityStoreFailed: Failed to store identity`

**Comment by Justinzobel** [comment]
I'll retry this today with a clean environment.
